# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-18 12:30
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='lim_unidade_federacao_a',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('nomeabrev', models.CharField(max_length=50)),
                ('geometriaaproximada', models.CharField(max_length=3)),
                ('sigla', models.CharField(max_length=3)),
                ('geocodigo', models.CharField(max_length=15)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
                ('tx_comentario_producao', models.CharField(max_length=250)),
                ('id_produtor', models.IntegerField(verbose_name='id_produtor')),
                ('id_elementoprodutor', models.IntegerField(verbose_name='id_elementoprodutor')),
            ],
        ),
    ]
