# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-18 13:16
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lim_unidade_federacao_a',
            name='geom',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(srid=4674),
        ),
    ]
